---
- name: Deployment of frontend
  run_once: true
  block:
    - name: Create a k8s namespace
      kubernetes.core.k8s:
        name: webapp
        api_version: v1
        kind: Namespace
        state: present

    - name: Ensure deployment of frontend
      kubernetes.core.k8s:
        definition: "{{ lookup('template', 'templates/%s' % item) | from_yaml_all | list }}"
        state: present
      loop:
        - nginx-configmap.yaml
        - webapp-configmap.yaml
        - webapp-secret.yaml
        - tls-secret.yaml
        - service.yaml
        - serviceaccount.yaml
        - ingressroute.yaml
        - deployment.yaml
        - django-migrate.yaml

    - name: Wait for frontend to be ready
      kubernetes.core.k8s:
        state: present
        kind: Deployment
        api_version: apps/v1
        wait: true
        wait_sleep: 10
        name: "frontend"
        namespace: "webapp"
        wait_timeout: 300
