---
- name: Deployment of frontend
  run_once: true
  block:
    - name: Ensure deployment of frontend
      kubernetes.core.k8s:
        definition: "{{ lookup('template', 'templates/%s' % item) | from_yaml_all | list }}"
        state: present
      loop:
        - nginx-configmap.yaml
        - webapp-configmap.yaml
        - webapp-secret.yaml
        - tls-secret.yaml
        - service.yaml
        - serviceaccount.yaml
        - ingressroute.yaml
        - deployment.yaml
        - django-migrate.yaml
