---
- name: Deployment of rest-api
  run_once: true
  block:
    - name: Ensure deployment of rest-api
      kubernetes.core.k8s:
        definition: "{{ lookup('template', 'templates/%s' % item) | from_yaml_all | list }}"
        state: present
      loop:
        - service.yaml
        - serviceaccount.yaml
        - ingressroute.yaml
        - deployment.yaml
