---
- name: Deployment of rest-api
  run_once: true
  block:
    - name: Create a k8s namespace
      kubernetes.core.k8s:
        name: webapp
        api_version: v1
        kind: Namespace
        state: present

    - name: Ensure deployment of rest-api
      kubernetes.core.k8s:
        definition: "{{ lookup('template', 'templates/%s' % item) | from_yaml_all | list }}"
        state: present
      loop:
        - service.yaml
        - serviceaccount.yaml
        - ingressroute.yaml
        - deployment.yaml

    - name: Wait for rest-api to be ready
      kubernetes.core.k8s:
        state: present
        kind: Deployment
        api_version: apps/v1
        wait: true
        wait_sleep: 10
        wait_condition:
          type: Ready
          status: "True"
        name: "rest-api"
        namespace: "webapp"
        wait_timeout: 120
