---
- name: Frontend Playbook
  hosts: all

  tasks:
    - name: Create webapp secret for environmental variables
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: v1
          kind: Secret
          type: Opaque
          metadata:
            name: "webapp-secret"
            namespace: "webapp"
          stringData:
            DJANGO_SECRET_KEY: { { webapp_secret_key } }
            DATABASE_NAME: autoreduction
            DATABASE_USERNAME: { { vault_db_username } }
            DATABASE_PASSWORD: { { vault_mysql_user_password } }
            DATABASE_HOST: { { vault_db_host } }
            ICAT_AUTH: simple
            ICAT_HOST: { { vault_icat_host } }
            ICAT_USER: { { vault_icat_username } }
            ICAT_PASSWORD: { { vault_icat_password } }
            SFTP_USERNAME: { { vault_sftp_username } }
            SFTP_PASSWORD: { { vault_sftp_password } }
            SFTP_HOST: { { vault_sftp_host } }
            SFTP_PORT: { { vault_sftp_port } }

    - name: Deploy Helm chart for frontend with values in template
      kubernetes.core.helm:
        name: frontend
        chart_ref: ../helm/charts/frontend
        release_namespace: webapp
        create_namespace: true
