---
- name: Deployment
  run_once: true
  block:
    - name: Deploy Helm chart for rest-api
      kubernetes.core.helm:
        name: rest-api
        chart_ref: ../helm-prod/charts/rest-api
        release_namespace: webapp
        create_namespace: true
        values:
          image:
            tag: "{{ api_tag }}"
