apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: qp-pvc
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "-1"
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: longhorn
  resources:
    requests:
      storage: {{ .Values.storage.size }}