apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "run-detection.fullname" . }}
  labels:
    {{- include "run-detection.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "run-detection.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "run-detection.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "run-detection.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: [ "sh", "-c"]
          # loop forever, outputting "yo" every 5 seconds
          args: ["while true; do echo 'yo' && sleep 5; done;"]
          envFrom:
            - secretRef:
                name: run-detection-secret
            - configMapRef:
                name: run-detection-config
          volumeMounts:
            - name: run-detection-vol
              mountPath: /run-detection/
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      initContainers:
      - name: init-run-detection
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        command: ["touch", "/run-detection/last_runs.csv"]
        volumeMounts:
          - name: run-detection-vol
            mountPath: /run-detection/
      volumes:
        - name: run-detection-vol
          persistentVolumeClaim:
            claimName: run-detection-pvc

      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
