apiVersion: batch/v1
kind: Job
metadata:
  name: django-migrations
  namespace: webapp
spec:
  ttlSecondsAfterFinished: 0
  template:
    spec:
      containers:
        - name: autoreduce-frontend
          image: ghcr.io/autoreduction/autoreduce-frontend:{{ frontend_tag }}
          workingDir: /home/isisautoreduce/fixtures
          command: ["/bin/sh"]
          args:
            - -c
            - >-
                autoreduce-webapp-manage migrate &&
                autoreduce-webapp-manage loaddata status_fixture software_fixture
          envFrom:
            - secretRef:
                name: webapp-secret
            - configMapRef:
                name: webapp-config
      restartPolicy: Never
  backoffLimit: 5
