apiVersion: v1
kind: ConfigMap
metadata:
  name: qp-config
data:
  DJANGO_ALLOWED_HOSTS: "*"
  DJANGO_SECRET_KEY: "YOUR-SECRET-KEY"
  DATABASE_NAME: "autoreduction"
  DATABASE_USERNAME: "test-user"
  DATABASE_PASSWORD: "pass"
  DATABASE_HOST: "127.0.0.1"
  DATABASE_PORT: "3306"
  ACTIVEMQ_USERNAME: "admin"
  ACTIVEMQ_PASSWORD: "admin"
  ACTIVEMQ_HOST: "127.0.1.1"
  ACTIVEMQ_PORT: "61613"
  ICAT_AUTH: "simple"
  ICAT_HOST: "YOUR-ICAT-WSDL-URL"
  ICAT_USER: "YOUR-ICAT-USERNAME"
  ICAT_PASSWORD: "YOUR-PASSWORD"
  CYCLE_USER: "admin"
  CYCLE_PASSWORD: "admin"
  CYCLE_UOWS_URL: "https://api.url.com/?wsdl"
  CYCLE_SCHEDULER_URL: "https://api.url.com/?wsdl"
  SFTP_USERNAME: "admin"
  SFTP_PASSWORD: "admin"
  SFTP_HOST: "127.0.1.1"
  SFTP_PORT: "22"
  KAFKA_BROKER_URL: "my-cluster-kafka-bootstrap:9092"
  KAFKA_TOPIC: "data_ready"
