apiVersion: v1
kind: ConfigMap
metadata:
  name: webapp-config
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "-1"
data:
  {{- if .Values.environment.production }}
  AUTOREDUCTION_PRODUCTION: "1"
  {{- end }}
  DJANGO_ALLOWED_HOSTS: "*" # Should be changed to actual allowed hosts once provisioned
  KAFKA_BROKER_URL: "autoreduce-cluster-kafka-bootstrap.kafka:9092"
  KAFKA_TOPIC: "data_ready"
  AUTOREDUCE_API_URL: "http://rest-api.webapp.svc.cluster.local:8001/api"
  DATABASE_NAME: autoreduction
  DATABASE_USERNAME: "root"
  DATABASE_PASSWORD: "password"
  DATABASE_HOST: "mysql"
  DATABASE_PORT: "3306"
