---
# tasks file for queue-processor
- name: Ensure cifs-utils is installed
  become: true
  ansible.builtin.package:
    name: cifs-utils
    state: present

- name: Create archive credentials Secret
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: v1
      kind: Secret
      type: Opaque
      metadata:
        name: cifs-csi-credentials
        namespace: queue-processor
      data:
        username: { { vault_archive_username | b64encode } }
        password: { { vault_archive_password | b64encode } }
        domain: { { vault_archive_domain | b64encode } }

- name: Ensure Helm repository is available
  kubernetes.core.helm_repository:
    name: csi-driver-smb
    repo_url: https://raw.githubusercontent.com/kubernetes-csi/csi-driver-smb/master/charts
    state: present

- name: Ensure csi-driver-smb is deployed
  kubernetes.core.helm:
    update_repo_cache: true
    name: csi-driver-smb
    namespace: kube-system
    create_namespace: true
    chart_ref: csi-driver-smb/csi-driver-smb
    state: present

- name: Deploy Helm chart for Queue Processor with values in template
  kubernetes.core.helm:
    name: queue-processor
    chart_ref: ../helm/charts/queue-processor
    release_namespace: queue-processor
    create_namespace: true
