- name: Deployment
  delegate_to: localhost
  run_once: true
  block:
    - name: Create qp namespace
      kubernetes.core.k8s:
        name: "queue-processor"
        api_version: v1
        kind: Namespace
        state: present

    - name: Deploy Helm chart for qp
      kubernetes.core.helm:
        name: queue-processor
        chart_ref: ../../../helm-prod/charts/queue-processor
        release_namespace: queue-processor
        create_namespace: true
        values:
          image:
            tag: "{{ qp_tag }}"
