apiVersion: v1
kind: ConfigMap
metadata:
  name: webapp-config
data:
  AUTOREDUCTION_PRODUCTION: "1"
  DJANGO_ALLOWED_HOSTS: "*" # Should be changed to actual allowed hosts once provisioned
  KAFKA_BROKER_URL: "my-cluster-kafka-bootstrap.kafka:9092"
  KAFKA_TOPIC: "data_ready"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-api-nginx
data:
  api.conf: |
    upstream app_server {
        server 127.0.0.1:8000 fail_timeout=0;
    }

    server {
        listen 80 default_server;
        listen [::]:80 default_server;
        server_name localhost;
        root /var/www/api;
        client_max_body_size 1G;

        access_log stdout;
        error_log  stderr;

        location /static/ {
            alias /var/www/api/;
            autoindex off;
        }

        location / {
            try_files $uri @django;
        }

        location @django {
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header Host $http_host;
            proxy_redirect off;
            proxy_pass http://app_server;
        }
    }
