apiVersion: apps/v1
kind: Deployment
metadata:
  name: rest-api
  namespace: webapp
  labels:
    app.kubernetes.io/instance: rest-api
    app.kubernetes.io/name: rest-api
    app.kubernetes.io/version: "1.0.0"
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: rest-api
      app.kubernetes.io/name: rest-api
  template:
    metadata:
      annotations:
        linkerd.io/inject: enabled
      labels:
        app.kubernetes.io/instance: rest-api
        app.kubernetes.io/name: rest-api
    spec:
      serviceAccountName: rest-api-service-account
      containers:
        - name: rest-api
          image: "ghcr.io/autoreduction/autoreduce-rest-api:{{ rest_api_tag }}"
          imagePullPolicy: IfNotPresent
          envFrom:
            - secretRef:
                name: webapp-secret
            - configMapRef:
                name: webapp-config
          ports:
            - name: http
              containerPort: 8001
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /alive
              port: 8005
            periodSeconds: 10
            failureThreshold: 10
          readinessProbe:
            httpGet:
              path: /ready
              port: 8005
            initialDelaySeconds: 10
            periodSeconds: 10
            failureThreshold: 3
