apiVersion: v1
kind: Service
metadata:
  name: {{ include "rest-api.fullname" . }}
  labels:
    {{- include "rest-api.labels" . | nindent 4 }}
spec:
  ports:
    - name: http
      port: {{ .Values.service.port }}
  selector:
    {{- include "rest-api.selectorLabels" . | nindent 4 }}
