apiVersion: batch/v1
kind: CronJob
metadata:
  name: run-detection-cron
spec:
  schedule: "* * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: autoreduce-run-detection
            image: ghcr.io/autoreduction/autoreduce-run-detection:latest
            imagePullPolicy: IfNotPresent
            command:
            - /bin/sh
            - -c
            - autoreduce-run-detection >> ~/job-output.log
          restartPolicy: OnFailure