apiVersion: v1
kind: Secret
metadata:
  name: autoreduce-user
  namespace: {{ strimzi_kafka_namespace }}
  labels:
    strimzi.io/cluster: {{ strimzi_kafka_cluster_name }}
type: Opaque
data:
  password: "{{ kafka_secrets.sasl_password | b64encode }}"
