apiVersion: v1
kind: Service
metadata:
  name: queue-processor
  namespace: queue-processor
  labels:
    app.kubernetes.io/instance: queue-processor
    app.kubernetes.io/name: queue-processor
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/instance: queue-processor
    app.kubernetes.io/name: queue-processor
