apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-initdb-config
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "-1"
data:
  initdb.sql: |
    USE autoreduction;
    CREATE USER 'autoreduce'@'%' IDENTIFIED BY 'password';
    GRANT ALL PRIVILEGES ON autoreduction.* TO 'autoreduce'@'%';