---
# the uid of the runtime user is important as it used to verify the identity
# of the user when interacting with ceph
- name: Add runtime user
  become: true
  ansible.builtin.user:
    name: isisautoreduce
    uid: "{{ vault_autoreduction_user_id }}"
    shell: /bin/bash
    groups: docker
    append: true

- name: Ensures ~/.autoreduce dir exists
  become: true
  file:
    path: /home/isisautoreduce/.autoreduce/
    state: directory
    owner: "isisautoreduce"
    group: "isisautoreduce"
    mode: "u=rwx,g=,o="
