# Install acl package required for Ansible to become non-root user
- name: Install acl package
  become: true
  ansible.builtin.package:
    name: acl
    state: present

# Start the container using the user in the Docker group (isisautoreduce)
- name: Start the container
  become: true
  become_user: isisautoreduce
  community.docker.docker_container:
    name: queue-processor
    image: ghcr.io/autoreduction/autoreduce:latest
    state: started
    pull: true
    env:
      AUTOREDUCTION_PRODUCTION: "true"
      DJANGO_ALLOWED_HOSTS: "*"
      DJANGO_SECRET_KEY: "{{ vault_webapp_secret_key }}"
      AUTOREDUCE_API_URL: "http://rest-api.webapp.svc.cluster.local:8001/api"
      ICAT_AUTH: "simple"
      DATABASE_NAME: "autoreduction"
      DATABASE_HOST: "172.16.100.152"
      DATABASE_PORT: "3306"
      DATABASE_USERNAME: "{{ db_secrets.username }}"
      DATABASE_PASSWORD: "{{ db_secrets.user_password }}"
      ICAT_HOST: "{{ icat_secrets.host }}"
      ICAT_USER: "{{ icat_secrets.username }}"
      ICAT_PASSWORD: "{{ icat_secrets.password }}"
      SFTP_USERNAME: "{{ sftp_secrets.username }}"
      SFTP_PASSWORD: "{{ sftp_secrets.password }}"
      SFTP_HOST: "{{ sftp_secrets.host }}"
      SFTP_PORT: "{{ sftp_secrets.port | string }}"
      KAFKA_BROKER_URL: "172.16.100.152:32698"
      KAFKA_TOPIC: "data_ready"
      KAFKA_SASL_USERNAME: "{{ kafka_secrets.sasl_username }}"
      KAFKA_SASL_PASSWORD: "{{ kafka_secrets.sasl_password }}"
      KAFKA_SASL_MECHANISM: "SCRAM-SHA-512"
      KAFKA_SECURITY_PROTOCOL: "SASL_PLAINTEXT"
    volumes:
      - /home/isisautoreduce/.autoreduce:/home/isisautoreduce/.autoreduce:rw
      - /instrument:/instrument:rw
      - /isis:/isis
    network_mode: host
    detach: true
    comparisons:
      image: strict
