- name: Start the container
  community.docker.docker_container:
    name: queue-processor
    image: ghcr.io/autoreduction/autoreduce:latest
    state: started
    pull: true
    env:
      AUTOREDUCTION_PRODUCTION: "true"
      DJANGO_ALLOWED_HOSTS: "*"
      DJANGO_SECRET_KEY: "{{ vault_webapp_secret_key }}"
      AUTOREDUCE_API_URL: "http://rest-api.webapp.svc.cluster.local:8001/api"
      ICAT_AUTH: "simple"
      DATABASE_NAME: "autoreduction"
      DATABASE_HOST: "172.16.100.152"
      DATABASE_PORT: "3306"
      DATABASE_USERNAME: "{{ vault_db_username }}"
      DATABASE_PASSWORD: "{{ vault_mysql_user_password }}"
      ICAT_HOST: "{{ vault_icat_host }}"
      ICAT_USER: "{{ vault_icat_username }}"
      ICAT_PASSWORD: "{{ vault_icat_password }}"
      SFTP_USERNAME: "{{ vault_sftp_username }}"
      SFTP_PASSWORD: "{{ vault_sftp_password }}"
      SFTP_HOST: "{{ vault_sftp_host }}"
      SFTP_PORT: "{{ vault_sftp_port | string }}"
      KAFKA_BROKER_URL: "172.16.100.152:32698"
      KAFKA_TOPIC: "data_ready"
      KAFKA_SASL_USERNAME: "{{ vault_kafka_sasl_username }}"
      KAFKA_SASL_PASSWORD: "{{ vault_kafka_sasl_password }}"
      KAFKA_SASL_MECHANISM: "{{ vault_kafka_sasl_mechanism }}"
      KAFKA_SECURITY_PROTOCOL: "{{ vault_kafka_security_protocol }}"
    network_mode: host
    detach: true
    comparisons:
      image: strict
