---
- name: Install ceph-common
  become: true
  ansible.builtin.package:
    name: ceph-common
    state: present
    update_cache: true

- name: "Create instrument (RB directories) mount directory"
  become: true
  ansible.builtin.file:
    path: /instrument/
    state: directory
    mode: 0755

- name: "Create Ceph key directory"
  become: true
  ansible.builtin.file:
    path: /etc/ceph/
    state: directory
    mode: 0700

- name: "Copy over the cephfs key"
  become: true
  ansible.builtin.template:
    src: deneb.key.j2
    dest: /etc/ceph/deneb.key
    owner: "root"
    group: "root"
    mode: 0700

- name: "Add instrument (RB directories) mount to fstab"
  become: true
  ansible.posix.mount:
    path: /instrument
    src: deneb-mon1.nubes.rl.ac.uk,deneb-mon2.nubes.rl.ac.uk,deneb-mon3.nubes.rl.ac.uk:/isis/instrument
    fstype: ceph
    opts: "name=isis_autoreduce,secretfile=/etc/ceph/deneb.key,noatime,_netdev"
    state: mounted
