---
- name: Deployment of mysql
  run_once: true
  block:
    - name: Create a k8s namespace
      kubernetes.core.k8s:
        name: webapp
        api_version: v1
        kind: Namespace
        state: present

    - name: Ensure deployment of mysql
      kubernetes.core.k8s:
        definition: "{{ lookup('template', 'templates/%s' % item) | from_yaml_all | list }}"
        state: present
      loop:
        - mysql-initdb.yaml
        - mysql-secret.yaml
        - service.yaml
        - serviceaccount.yaml
        - ingressroute.yaml
        - pv.yaml
        - deployment.yaml
