apiVersion: apps/v1
kind: Deployment
metadata:
  name: autoreduce-rest-api
  labels:
    app: autoreduce-rest-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: autoreduce-rest-api
  template:
    metadata:
      labels:
        app: autoreduce-rest-api
    spec:
      containers:
        - name: autoreduce-rest-api
          image: ghcr.io/autoreduction/autoreduce-rest-api:latest
          envFrom:
            - configMapRef:
                name: api-config
          ports:
            - containerPort: 8001
---
apiVersion: v1
kind: Service
metadata:
  name: rest-api-service
spec:
  selector:
    app: autoreduce-rest-api
  ports:
      - port: 8001
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: rest-api-ingress
  annotations:
    kubernetes.io/ingress.class: traefik
spec:
  entryPoints:
    - web
  routes:
    - match: PathPrefix(`/api`)
      kind: Rule
      services:
        - name: rest-api-service
          port: 8001
