apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
metadata:
  name: quickstart
spec:
  version: 8.1.0
  count: 1
  elasticsearchRef:
    name: quickstart
  config:
    server.basePath:
      - "/kibana"
    server.publicBaseUrl:
      - "https://reduce.isis.cclrc.ac.uk/kibana"
