---
- name: Create Kafka Cluster
  kubernetes.core.k8s:
    state: present
    namespace: "{{ strimzi_kafka_namespace }}"
    definition: "{{ lookup('template', 'templates/cluster.yaml.j2') | from_yaml }}"

- name: Wait for Kafka Cluster
  kubernetes.core.k8s:
    state: present
    kind: Kafka
    api_version: v1beta2
    wait: yes
    wait_sleep: 10
    wait_condition:
      type: Ready
      status: "True"
    name: "{{ strimzi_kafka_cluster_name }}"
    namespace: "{{ strimzi_kafka_namespace }}"
    wait_timeout: 1000

- name: Create Kafka Topic
  kubernetes.core.k8s:
    state: present
    definition: "{{ lookup('template', 'templates/topic.yaml.j2') | from_yaml }}"

- name: Create Kafka User
  kubernetes.core.k8s:
    state: present
    definition: "{{ lookup('template', 'templates/user.yaml.j2') | from_yaml }}"
