---
- name: Create Kafka namespace
  kubernetes.core.k8s:
    name: "{{ strimzi_kafka_namespace }}"
    api_version: v1
    kind: Namespace
    state: present

- name: Ensure Helm repository is available
  kubernetes.core.helm_repository:
    name: strimzi
    repo_url: https://strimzi.io/charts/
    state: present

- name: Ensure Strimzi Operator is deployed
  kubernetes.core.helm:
    name: strimzi
    namespace: "{{ strimzi_kafka_namespace }}"
    chart_ref: strimzi/strimzi-kafka-operator
    values:
      watchAnyNamespace: true
    state: present

- name: Wait for Kafka Deployment
  kubernetes.core.k8s:
    state: present
    kind: Deployment
    wait: true
    wait_sleep: 10
    wait_condition:
      type: Available
      status: "True"
    name: "strimzi-cluster-operator"
    namespace: "{{ strimzi_kafka_namespace }}"
    wait_timeout: 1000
