---
- name: Deploy autoreduction services
  hosts: prod,dev

  roles:
    - role: traefik
      tags: ["traefik", "autoreduce"]
    - role: strimzi_kafka
      tags: ["strimzi_kafka", "autoreduce"]
    - role: mysql
      tags: ["mysql", "webapp", "autoreduce"]
    - role: frontend
      tags: ["frontend", "webapp", "autoreduce"]
    - role: rest_api
      tags: ["rest_api", "webapp", "autoreduce"]
    - role: run_detection
      tags: ["run_detection", "autoreduce"]
    - role: queue_processor
      tags: ["queue_processor"]

- name: Deploy qp external services
  hosts: qp_external_prod,qp_external_dev
  vars:
    pip_install_packages:
      - name: docker
  roles:
    - role: geerlingguy.pip
      become: true
      tags: ["qp_external"]
    - role: geerlingguy.docker
      become: true
      tags: ["qp_external"]
    - role: qp_external
      tags: ["qp_external"]
