---
- name: Deploy autoreduction services
  hosts: local

  roles:
    - role: mysql
      tags: ["mysql", "webapp", "autoreduce"]
    - role: frontend
      tags: ["frontend", "webapp", "autoreduce"]
    - role: rest-api
      tags: ["rest-api", "webapp", "autoreduce"]
    - role: run-detection
      tags: ["run-detection", "autoreduce"]
    - role: queue-processor
      tags: ["queue-processor", "autoreduce"]
    - role: strimzi_kafka
      tags: ["strimzi_kafka", "autoreduce"]

- name: Deploy qp external services
  hosts: openstack
  roles:
    - role: geerlingguy.docker
      become: true
      tags: ["qp-external"]
    - role: qp-external
      tags: ["qp-external"]
