apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: frontend-ingress-tls
  annotations:
    kubernetes.io/ingress.class: traefik
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`reduce.isis.cclrc.ac.uk`)
      kind: Rule
      middlewares:
        - name: frontend-gunicorn-linkerd-middleware
      services:
        - name: frontend-gunicorn
          port: {{ .Values.service.gunicorn.port }}
  tls:
    secretName: ssl-cert
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: frontend-ingress-static-tls
  annotations:
    kubernetes.io/ingress.class: traefik
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`reduce.isis.cclrc.ac.uk`) && PathPrefix(`/static`) 
      kind: Rule
      middlewares:
        - name: frontend-nginx-linkerd-middleware
      services:
        - name: frontend-nginx
          port: {{ .Values.service.nginx.port }}
  tls:
    secretName: ssl-cert
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: frontend-gunicorn-linkerd-middleware
spec:
  headers:
    customRequestHeaders:
      l5d-dst-override: "frontend-gunicorn.webapp.svc.cluster.local:{{ .Values.service.gunicorn.port }}"
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: frontend-nginx-linkerd-middleware
spec:
  headers:
    customRequestHeaders:
      l5d-dst-override: "frontend-nginx.webapp.svc.cluster.local:{{ .Values.service.nginx.port }}"
