apiVersion: v1
kind: Service
metadata:
  name: {{ include "frontend.fullname" . }}-nginx
  labels:
    {{- include "frontend.labels" . | nindent 4 }}
spec:
  ports:
    - name: http
      port: {{ .Values.service.nginx.port }}
  selector:
    {{- include "frontend.selectorLabels" . | nindent 4 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "frontend.fullname" . }}-gunicorn
  labels:
    {{- include "frontend.labels" . | nindent 4 }}
spec:
  ports:
    - name: gunicorn
      port: {{ .Values.service.gunicorn.port }}
  selector:
    {{- include "frontend.selectorLabels" . | nindent 4 }}