apiVersion: v1
kind: ServiceAccount
metadata:
  name: queue-processor-service-account
  namespace: queue-processor
  labels:
    app.kubernetes.io/instance: queue-processor
    app.kubernetes.io/name: queue-processor
