apiVersion: v1
kind: ConfigMap
metadata:
  name: webapp-config
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "-1"
data:
  #AUTOREDUCTION_PRODUCTION: "1"
  DJANGO_ALLOWED_HOSTS: "*" # Should be changed to actual allowed hosts once provisioned
  KAFKA_BROKER_URL: "my-cluster-kafka-bootstrap.kafka:9092"
  KAFKA_TOPIC: "data_ready"
