---
- name: Deployment of run-detection
  run_once: true
  block:
    - name: Ensure deployment of run-detection
      kubernetes.core.k8s:
        definition: "{{ lookup('template', 'templates/%s' % item) | from_yaml_all | list }}"
        state: present
      loop:
        - run-detection-configmap.yaml
        - run-detection-secret.yaml
        - pv.yaml
        - serviceaccount.yaml
        - cronjob.yaml
