apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: run-detection-pvc
  namespace: run-detection
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 2Gi
