name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint-ansible:
    name: Ansible Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Ansible
        uses: ansible-community/ansible-lint-action@main

  deployment-test:
    name: Deployment Test
    runs-on: ubuntu-latest
    env:
      PY_COLORS: '1'
      ANSIBLE_FORCE_COLOR: '1'
    strategy:
      matrix:
        deployment: [webapp, strimzi_kafka, queue_processor]
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.8"

      - name: Install dependencies
        run: |
          pip install --upgrade pip ansible kubernetes
          ansible-galaxy install -r ./ansible/requirements.yaml

      - name: Setup mount points
        run: |
          sudo mkdir /isis
          sudo mkdir /instrument

      - name: Create k8s Kind Cluster
        uses: helm/kind-action@v1.4.0

      - name: Setup Helm
        uses: azure/setup-helm@v3
        id: install

      - name: Create file for vault password
        run: |
          echo ${{ secrets.DEV_VAULT_KEY }} > vault_password.txt
          chmod 0600 vault_password.txt
          mv vault_password.txt /tmp/vault_password.txt

      - name: Install Traefik
        working-directory: ./ansible
        run: >
          ansible-playbook autoreduce.yaml
          --tags traefik
          --limit dev
          --vault-password-file=/tmp/vault_password.txt
          -e 'ansible_python_interpreter=/opt/hostedtoolcache/Python/3.8.13/x64/bin/python3'

      - name: Run ansible-playbook
        working-directory: ./ansible
        run: >
          ansible-playbook autoreduce.yaml
          --tags ${{ matrix.deployment }}
          --limit dev
          --vault-password-file=/tmp/vault_password.txt
          -e 'ansible_python_interpreter=/opt/hostedtoolcache/Python/3.8.13/x64/bin/python3'

      - name: Delete vault password file
        run: |
          rm -f /tmp/vault_password.txt
