name: CI

on:
  push:
  pull_request:
    branches: [main]

jobs:
  lint-ansible:
    name: Ansible Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Ansible
        uses: ansible-community/ansible-lint-action@main

  e2e-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.8"

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install ansible
          pip install kubernetes
          ansible-galaxy install -r ./ansible/requirements.yaml
          which pip
          which pip3
          which python3

      - name: Create k8s Kind Cluster
        uses: helm/kind-action@v1.3.0

      - name: Setup Helm
        uses: azure/setup-helm@v3
        id: install

      - name: Install Linkerd
        run: |
          curl --proto '=https' --tlsv1.2 -sSfL https://run.linkerd.io/install | sh
          export PATH=$PATH:/home/runner/.linkerd2/bin
          linkerd check --pre
          linkerd install | kubectl apply -f -
          linkerd check

      - name: Install Traefik Helm Chart
        run: |
          helm repo add traefik https://helm.traefik.io/traefik
          helm repo update
          helm install traefik traefik/traefik

      - name: Run playbook
        uses: dawidd6/action-ansible-playbook@v2
        with:
          playbook: ./ansible/autoreduce.yaml
          # Optional, encrypted vault password
          vault_password: ${{secrets.VAULT_KEY}}
          # Optional, literal inventory file contents
          inventory: |
            [local]
            localhost ansible_host=localhost ansible_connection=local ansible_python_interpreter=/opt/hostedtoolcache/Python/3.8.13/x64/bin/python3
          # Optional, additional flags to pass to ansible-playbook
          options: |
            --tags webapp
