---
- name: Deployment of queue-processor
  run_once: true
  block:
    - name: Ensure deployment of queue-processor
      kubernetes.core.k8s:
        definition: "{{ lookup('template', 'templates/%s' % item) | from_yaml_all | list }}"
        state: present
      loop:
        - qp-configmap.yaml.j2
        - qp-secret.yaml.j2
        - service.yaml.j2
        - serviceaccount.yaml.j2
        - deployment.yaml.j2
