---
- name: Deployment of queue-processor
  run_once: true
  block:
    - name: Create a k8s namespace
      kubernetes.core.k8s:
        name: queue-processor
        api_version: v1
        kind: Namespace
        state: present

    - name: Deploy resources needed for queue-processor
      kubernetes.core.k8s:
        definition: "{{ lookup('template', 'templates/%s' % item) | from_yaml_all | list }}"
        state: present
      loop:
        - qp-configmap.yaml.j2
        - qp-secret.yaml.j2
        - service.yaml.j2
        - serviceaccount.yaml.j2

    - name: Deploy queue-processor
      kubernetes.core.k8s:
        state: present
        definition: "{{ lookup('template', 'templates/deployment.yaml') | from_yaml }}"
        wait: true
        wait_condition:
          type: Available
          status: "True"
          reason: MinimumReplicasAvailable
